=== U-235-92/code-gym/src/main/java/aq/gym/xml/sax_item_analizer/item_xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="items" type="itemsType" />
    <xs:element name="item" type="itemType" />
    <xs:element name="name" type="xs:string" />
    <xs:element name="characteristic" type="xs:string" />
    <xs:element name="expiration" type="xs:date" />
    <xs:attribute name="id" type="xs:ID" />
    
    <!-- Items Type defenintion -->
    <xs:complexType name="itemsType">
        <xs:sequence>
            <xs:element ref="item" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <!-- Item Type defenintion -->
    <xs:complexType name="itemType">
        <xs:sequence>
            <xs:element ref="name" />
            <xs:element ref="characteristic" />
            <xs:element ref="expiration" />
        </xs:sequence>
        <xs:attribute ref="id" />
    </xs:complexType>
</xs:schema>

=== U-235-92/code-gym/src/main/java/aq/gym/xml/stax_item_analizer/item_xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="item_xsd.xsd">
    <item id="i-1">
        <name>Dymatize Elite 100% Whey Protein 907</name>
        <characteristic>Chocolate</characteristic>
        <expiration>2025-12-12</expiration>
    </item>
    <item id="i-2">
        <name>Dymatize Elite 100% Whey Protein 907</name>
        <characteristic>Strawberry</characteristic>
        <expiration>2025-12-12</expiration>
    </item>
    <item id="i-3">
        <name>Dymatize Elite 100% Whey Protein 907</name>
        <characteristic>Vanila</characteristic>
        <expiration>2025-12-12</expiration>
    </item>
    <item id="i-4">
        <name>Optimum Nutrition 100% Whey Gold Standard 909</name>
        <characteristic>White Chocolate</characteristic>
        <expiration>2026-11-22</expiration>
    </item>
    <item id="i-5">
        <name>BSN DNA Whey 838 Ð³</name>
        <characteristic>Banana</characteristic>
        <expiration>2027-05-08</expiration>
    </item>
    <item id="i-6">
        <name>Scitec Nutrition 100% Whey Protein Proffessional 920</name>
        <characteristic>Coconut</characteristic>
        <expiration>2028-08-05</expiration>
    </item>
</items>
