=== U-235-92/code-gym/src/main/java/aq/gym/xml/dom_book_analizer/books_xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="books" type="booksType" />
    <xs:element name="book" type="bookType" />
    <xs:element name="title" type="xs:string" />
    <xs:element name="author" type="authorType" />
    <xs:element name="firstname" type="xs:string" />
    <xs:element name="lastname" type="xs:string" />
    <xs:attribute name="isbn" type="xs:string" />
    
    <!-- Books Type defenintion -->
    <xs:complexType name="booksType">
        <xs:sequence>
            <xs:element ref="book" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <!-- Book Type defenintion -->
    <xs:complexType name="bookType">
        <xs:sequence>
            <xs:element ref="title" minOccurs="1" maxOccurs="1" />
            <xs:element ref="author" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute ref="isbn" use="required" />
    </xs:complexType>
    
    <!-- Author Type defenintion -->
    <xs:complexType name="authorType">
        <xs:sequence>
            <xs:element ref="firstname" minOccurs="1" maxOccurs="1" />
            <xs:element ref="lastname" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== U-235-92/code-gym/src/main/java/aq/gym/xml/dom_book_analizer/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="books_xsd.xsd">
    <book isbn="9785389189768">
        <title>Вечный Зов</title>
        <author>
            <firstname>Анатолий</firstname>
            <lastname>Иванов</lastname>
        </author>
    </book>
    <book isbn="9785389149885">
        <title>Спартак</title>
        <author>
            <firstname>Рафаэлло</firstname>
            <lastname>Джованьоли</lastname>
        </author>
    </book>
    <book isbn="9785040307869">
        <title>Java. Методы программирования</title>
        <author>
            <firstname>Игорь</firstname>
            <lastname>Блинов</lastname>
        </author>
        <author>
            <firstname>Валерий</firstname>
            <lastname>Романчик</lastname>
        </author>
    </book>
    <book isbn="9785041567132">
        <title>Джен Эйр</title>
        <author>
            <firstname>Шарлотта</firstname>
            <lastname>Бронте</lastname>
        </author>
    </book>
    <book isbn="9785389013230">
        <title>Грозовой перевал</title>
        <author>
            <firstname>Шарлотта</firstname>
            <lastname>Бронте</lastname>
        </author>
    </book>
</books>
