=== U-235-92/code-gym/src/main/java/aq/gym/xml/api_using_examples/LibraryXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<!-- LIBRARY ELEMENT -->
	<xs:element name="library">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="book" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute ref="lib_name" use="required" />
		</xs:complexType>
	</xs:element>
	<!-- BOOK ELEMENT -->
	<xs:element name="book">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title" />
				<xs:element ref="author" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute ref="id" use="required" />
			<xs:attribute ref="type" use="required" />
		</xs:complexType>
	</xs:element>
	<!-- TITLE ELEMENT -->
	<xs:element name="title" type="xs:string" />
	<!-- AUTHOR ELEMENT -->
	<xs:element name="author" type="xs:string" />
	<!-- ATRIBUTES -->
	<xs:attribute name="lib_name" type="xs:string" />
	<xs:attribute name="id" type="xs:ID" />
	<xs:attribute name="type" type="xs:string" />
</xs:schema>

=== U-235-92/code-gym/src/main/java/aq/gym/xml/api_using_examples/LibraryDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<library lib_name="Old town library"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="LibraryXSD.xsd">
	<book id="BN-2" type="Роман-эпопея">
		<title>Сегун</title>
		<author>Джеймс Клавелл</author>
	</book>
	<book id="BN-1" type="Сатирический роман">
		<title>Бравый солдат Швейк</title>
		<author>Ярослав Гашек</author>
	</book>
	<book id="BN-3" type="Роман">
		<title>Шамал</title>
		<author>Джеймс Клавелл</author>
	</book>
	<book id="BN-7" type="Информатика">
		<title>Java для начинающих</title>
		<author>Андрей Андреев</author>
	</book>
	<book id="BN-4" type="Роман-эпопея">
		<title>Война и мир</title>
		<author>Лев Толстой</author>
	</book>
	<book id="BN-5" type="Информатика">
		<title>Java полное руководство</title>
		<author>Герберт Шилдт</author>
	</book>
	<book id="BN-6" type="Информатика">
		<title>Java. Методы программирования</title>
		<author>Валерий Романчик</author>
		<author>‎Игорь Блинов</author>
	</book>
</library>

=== U-235-92/code-gym/src/main/java/aq/gym/xml/api_using_examples/LibraryDocumentNEW.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	lib_name="New library" xsi:noNamespaceSchemaLocation="LibraryXSD.xsd">
	<book id="SN-1" type="Информатика">
		<title>Java. Полное руководство</title>
		<author>Герберт Шилдт</author>
	</book>
	<book id="SN-2" type="Проза">
		<title>Сборник стихов Пушкина</title>
		<author>Александ Пушкин</author>
	</book>
	<book id="SN-3" type="Фантастика">
		<title>Приключения Алисы</title>
		<author>Александ Пушкин</author>
	</book>
	<book id="SN-4" type="Фантастика">
		<title>Все обо всем</title>
		<author>Иван Иванов</author>
		<author>Петр Петров</author>
	</book>
</library>
